# version:     "0026--06-Sep-2022"
copyright: "2022"
author: "nlexi"
name: "Nicholas Lexi"
title: "OS222: Operating Systems 2022-2"
githublink: "https://github.com/catherineeangel/os222"
myloglink: "/TXT/mylog.txt"
tarballlink: "https://os.vlsm.org/Log/NLexi.tar.bz2.txt"
encoding: UTF-8
markdown: kramdown
input: GFM
hard_wrap: false
github: [metadata]
